const { createBot, createProvider, createFlow, addKeyword } = require('@bot-whatsapp/bot')

const QRPortalWeb = require('@bot-whatsapp/portal')
const BaileysProvider = require('@bot-whatsapp/provider/baileys')
const MockAdapter = require('@bot-whatsapp/database/mock')

const flowTecGestionProducEditorial = addKeyword(['14']).addAnswer([
    '📄 *Tecnicatura en Gestión y Producción Editorial*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',

    '\n*PRIMER AÑO*',
    '1	Introducción al campo editorial',
    '2	Taller de lectura y escritura académica y del campo editorial',
    '3	Gramática, norma y discurso I',
    '4	Taller de Edición I',
    '5	Teorías de la Gestión Editorial',
    '6	Gramática, norma y discurso II',
    '7	Comunicación y organizaciones',

    '\n*SEGUNDO AÑO*',
    '8 Corrección de estilo',
    '9 Políticas editoriales',
    '10 Taller de edición II',
    '11 Semiótica aplicada',
    '12 Promoción, distribución y comercialización editorial',
    '13 Calidad de gestión y administración editorial',
    '14 Práctica profesionalizante I',

    '\n*TERCER AÑO*',
    '15 Taller de diseño gráfico y maquetación',
    '16 Taller de edición III: producción editorial multimedial',
    '17 Legislación: derechos editoriales y del autor',
    '18 Catalogación y registro editorial',
    '19 Seminario I: Género, Comunicación, Sociedad y Políticas Editoriales',
    '20 Optativa',
    '21 Seminario II: Gestión de la Infraestructura y la tecnología editorial',
    '22 Práctica profesionalizante II',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifTecUnivGestyProdEditWeb.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowLicTrabajoSocial = addKeyword(['13']).addAnswer([
    '📄 *Licenciatura en Trabajo Social*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Introducción al Trabajo Social',
    '2	Metodología del Trabajo Social',
    '3	Problemática Filosófica Contemporánea y Trabajo Social',
    '4	Antropología Social y Cultural',
    '5	Historia Social Argentina y Latinoamericana',
    '6	Teórias de Desarrollo, Teorías del Estado y Políticas Públicas',
    '7	Género y Derechos Humanos',

    '\n*SEGUNDO AÑO*',
    '8	Trabajo Social con Grupos I',
    '9 Trabajo Social con Grupos II',
    '10 Planeamiento y Evaluación en Trabajo Social',
    '11 Trabajo Social e Investigación Social I',
    '12 Teoría Social Clásica en Trabajo Social',
    '13 Psicología Social',
    '14 Práctica de Recursos de la Comunidad',

    '\n*TERCER AÑO*',
    '15 Trabajo Social Comunitario',
    '16 Trabajo Social e Investigación Social II',
    '17 Teorías Sociales Contemporáneas en Trabajo Social',
    '18 Sociedades Complejas y Campesinas',
    '19 Salud, Salud Pública y Trabajo Social',
    '20 Práctica de Trabajo Social con Grupos',

    '\n*CUARTO AÑO*',
    '21 Trabajo Social Familiar I',
    '22 Problemática Social Argentina, Regional y Sur Andina',
    '23 Economía Social y Políticas Económicas',
    '24 Sistemas de Protección Social',
    '25 Psicología Evolutiva',
    '26 Práctica de Trabajo Social y Comunitario',

    '\n*QUINTO AÑO*',
    '27 Trabajo Social Familiar II',
    '28 Seminario de Integración Metológica y Diseño de Tesis',
    '29 Administración y Gerenciamiento Organizaciones y Servicios Sociales',
    '30 Práctica de Trabajo Social Familiar',
    '31 TRABAJO FINAL DE TESIS: Obtención del Título LICENCIADO EN TRABAJO SOCIAL',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifLicTrabSocial.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowTecLicTurismo = addKeyword(['12']).addAnswer([
    '📄 *Tecnicatura y Licenciatura en Turismo*',
    'Sede: Purmamarca y El Carmen',
    '📄 Materias de la carrera',

    '\n*PRIMER AÑO*',
    '1	Inglés Turístico 1',
    '2	Geografía de Recursos Turísticos',
    '3	Introducción al Turismo',
    '4	Principios de administración y Contabilidad',
    '5	Procesos históricos Argentinos y Jujeños',
    '6	Antropología y Turismo',
    '7	Arte y Arquitectura Colonial',

    '\n*SEGUNDO AÑO*',
    '8 Inglés Turístico 2',
    '9 Productos turísticos y atractivos turísticos de la Región',
    '10 Gestión del Patrimonio',
    '11 Agencias de Viaje',
    '12 Formulación y financiamiento de proyectos turísticos',
    '13 Informática aplicada al Turismo',
    '14 Planificación estratégica de destinos turísticos',
    '15 Organización y operación de empresas turísticas',

    '\n*TERCER AÑO*',
    '16 Inglés Turístico 3',
    '17 Teoría y Técnicas de la Estructura y los procesos administrativos',
    '18 Relaciones humanas y públicas',
    '19 Derecho y legislación Turística',
    '20 Turismo Sustentable y Desarrollo Local',
    '21 Gestión de Calidad Turística',
    '22 Portugués Turístico 1',
    '23 Metodología de la Investigación 1',
    '24 Práctica profesionalizante',
    '*TÍTULO INTERMEDIO: TÉCNICO UNIVERSITARIO EN TURISMO*',

    '\n*CUARTO AÑO*',
    '25 Gestión de destinos turísticos sustentables',
    '26 Metodología de la Investigación 2',
    '27 Gestión de Servicios hoteleros',
    '28 Francés',
    '29 Portugués Turístico 2',
    '30 Gestión de Calidad Turística',
    '31 Comercialización de productos y servicios turísticos',
    '32 Gestión del uso turístico de espacios protegidos',
    '33 Taller de Tesis',
    '*TÍTULO FINAL: LICENCIADO EN TURISMO*',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifTecUnivGestyProdEditWeb.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])

const flowLicLetras = addKeyword(['11']).addAnswer([
    '📄 *Licenciatura en Letras*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Introducción a la Literatura',
    '2	Introducción a la Historia: Historia Social y del Arte',
    '3	Filosofía',
    '4	Gramática I',
    '5	Latín I',
    '6	Gramática II',
    '7	Latin II',
    '8 Literaturas Clásicas',

    '\n*SEGUNDO AÑO*',
    '9 Lingüistica',
    '10 Literatura Española I',
    '11 Teoría y Crítica Literaria',
    '12 Literatura Española II',
    '13 Literatura Europea I',
    '14 Literatura Latinoamericana I',

    '\n*TERCER AÑO*',
    '15 Literatura Latinoamericana II',
    '16 Literatura Argentina I',
    '17 Historia de la Lengua',
    '18 Griego I',
    '19 Literatura Argentina II',
    '20 Literatura Europea II',
    '21 Griego II',

    '\n*CUARTO AÑO*',
    '22 Lógica',
    '23 Antropología Filosófica',
    '24 Taller Literario',
    '25 Literateratura del NOA',
    '26 Lengua Extranjera Nivel I',
    '27 Lengua Extranjera Nivel II',

    '\n*QUINTO AÑO*',
    '28 Metodología de la Investigación',
    '29 Filosofía del Lenguaje',
    '30 Teoría y Crítica Literaria II',
    '31 Seminario vinculado a Temáticas Literarias',
    '32 Seminario vinculado a Temáticas Lingüisticas, Semánticas o Gramaticales.',
    '33 Tesina Final',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifLicLetras.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowProfEnLetras = addKeyword(['10']).addAnswer([
    '📄 *Profesorado en Letras*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Introducción a la Literatura',
    '2	Introducción a la Historia: Historia Social y del Arte',
    '3	Filosofía',
    '4	Gramática I',
    '5	Latín I',
    '6	Gramática II',
    '7	Latin II',
    '8 Literaturas Clásicas',

    '\n*SEGUNDO AÑO*',
    '9 Lingüistica',
    '10 Literatura Española I',
    '11 Teoría y Crítica Literaria',
    '12 Psicología',
    '13 Pedagogía. Organización y Administración Escolar',
    '14 Literatura Española II',
    '15 Literatura Europea I',
    '16 Literatura Latinoamericana I',
    '17 Psicología Evolutiva',

    '\n*TERCER AÑO*',
    '18 Literatura Latinoamericana II',
    '19 Literatura Argentina I',
    '20 Historia de la Lengua',
    '21 Griego I',
    '22 Didáctica',
    '23 Literatura Argentina II',
    '24 Literatura Europea II',
    '25 Griego II',

    '\n*CUARTO AÑO*',
    '26 Lógica',
    '27 Antropología Filosófica',
    '28 Lengua Extranjera Moderna Nivel I',
    '29 Lengua Extranjera Moderna Nivel II',
    '30 Práctica y Residencia',
    '31 Lengua Extranjera Moderna Nivel I: Inglés I – Francés I',
    '31 Lengua Extranjera Moderna Nivel I: Inglés I – Francés II',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifProfLetras.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowProfHistoria = addKeyword(['09']).addAnswer([
    '📄 *Profesorado en Historia*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Introducción a la Historia',
    '2	Técnicas de Estudio',
    '3	Antropología Social y Cultural',
    '4	Procesos Mundiales I',
    '5	Sociología',
    '6	Pensamiento y Cultura Andino',
    

    '\n*SEGUNDO AÑO*',
    '7	Historiografía',
    '8 Procesos Mundiales II',
    '9 Procesos Americanos I',
    '10 Procesos Americanos II',
    '11 Procesos Mundiales III',
    '12 Etnohistoria Andina',

    '\n*TERCER AÑO*',
    '13 Procesos de Historia Argentina y Regional I',
    '14 Psicología Educacional',
    '15 Procesos Americanos III',
    '16 Optativa I',
    '17 Procesos de Historia Argentina y Regional II',
    '18 Filosofía de la Historia',
    '19 Planeamiento de la Educación',
    '20 Procesos Mundiales IV',

    '\n*CUARTO AÑO*',
    '21 Práctica y Residencia',
    '22 Procesos Americanos IV',
    '23 Didáctica General',
    '24 Optativa II',
    '25 Procesos de Historia Agentina y Regional III',
    '26 Didáctica de la Historia',
    '27 Investigación Educativa en Historia',
    '28 Idioma I',
    '29 Idioma II',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifProfHistoria.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowLicEnHistoria = addKeyword(['08']).addAnswer([
    '📄 *Licenciatura en Historia*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Introducción a la Historia',
    '2	Técnicas de Estudio',
    '3	Antropología Social y Cultural',
    '4	Pensamiento y Cultura Andino',
    '5	Procesos Mundiales I',
    '6	Sociología',

    '\n*SEGUNDO AÑO*',
    '7	Historiografía',
    '8 Procesos Mundiales II',
    '9 Procesos Americanos I',
    '10 Procesos Americanos II',
    '11 Procesos Mundiales III',
    '12 Etnohistoria Andina',

    '\n*TERCER AÑO*',
    '13 Procesos de Historia Argentina y Regional I',
    '14 Metodología de Investigación Histórica I',
    '15 Procesos Americanos III',
    '16 Procesos de Historia Argentina y Regional II',
    '17 Filosofía de la Historia',
    '18 Metodología de Investigación Histórica II',
    '19 Procesos Mundiales IV',

    '\n*CUARTO AÑO*',
    '20 Seminario de Tésis',
    '21 Procesos Americanos IV',
    '22 Optativa I',
    '23 Seminario I',
    '24 Procesos de Historia Agentina y Regional III',
    '25 Seminario II',
    '26 Optativa II',
    '27 Idioma I',
    '28 Idioma II',
    '29 Tesis',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifLicHistoria.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowProfYLicFilosofia = addKeyword(['07']).addAnswer([
    '📄 *Profesorado y Licenciatura en Filosofía*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Filosofía',
    '2	Historia de la Filosofía Antigua',
    '3	Introducción a la Historia: Historia Social y del Arte',
    '4	Lógica',
    '5	Introducción a la Literatura',
    '6	Problemática Educativa',
    '7	Teoría y Metodología de la Historia de las Ideas Latinoamericanas',

    '\n*SEGUNDO AÑO*',
    '8 Gnoseología',
    '9 Historia de la Filosofía Medieval',
    '10 Historia de la Filosofía Moderna',
    '11 Antropología Filosófica',
    '12 Ética',
    '13 Idioma Moderno: Inglés I o Francés I',
    '14 Psicología Eduacional',
    '15 Filosofía de la Educación',

    '\n*TERCER AÑO*',
    '16 Epistemología',
    '17 Historia de la Filosofía Contemporánea',
    '18 Estética',
    '19 Metafísica',
    '20 Seminario de Pensamiento Argentino y Latinoamericano',
    '21 Didactica General',
    '22 Idioma Moderno: Inglés II o Francés II',

    '\n*CUARTO AÑO*',
    '23 Filosofía de la Historia',
    '24 Filosofía del Lenguaje',
    '25 Filosofía Política',
    '26 Filosofía de la Tecnología',
    '27 Didáctica de la Filosofía',
    '28 Seminario de Pensamiento Andino',
    '29 Optativa I',
    '30 Módulo de Práctica y Residencia',
    '31 Módulo de Trabajo Final de Tesis',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifProfLicFilosofia.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowProfEducSalud = addKeyword(['06']).addAnswer([
    '📄 *Profesorado en Educación para la Salud*',
    'Sede: San Salvador de Jujuy y San Pedro',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Introducción a la Educación para la Salud',
    '2	Psicología Social',
    '3	Ecología Humana',
    '4	Psicología Evolutiva',
    '5	Pedagogía',
    '6	Antropología Filosófica',
    '7	Antropología Social y Cultural',

    '\n*SEGUNDO AÑO*',
    '8	Problemática Sanitaria I',
    '9 Comunicación en Salud',
    '10 Didáctica',
    '11 Salud y Salud Pública',
    '12 Tecnología Educativa',
    '13 Epidemiología Y Estadística',
    '14 Informática',

    '\n*TERCER AÑO*',
    '15 Problemática Sanitaria II',
    '16 Investigación Social Aplicada al Campo de la Salud',
    '17 Legislación Aplicada',
    '18 Sujeto del Aprendizaje',
    '19 Organización y Desarrollo de la Comunidad',
    '20 Planeamiento de la Educación para la Salud',
    '21 Salud Ocupacional',

    '\n*CUARTO AÑO*',
    '22 Seminario: Ciencia, Metodología y Educación para la Salud',
    '23 Teoría y Práctica de la Enseñanza en Educación para la Salud',
    '24 Análisis Institucional aplicado al Campor de la Salud',
    '25 Política Educacional y Legislación',
    '26 Planeamiento de la Educación para la Salud II',
    '27 Taller Formación Docente y Construcción del rol docente en la Educación para la Salud',
    '28 Taller Sistematización de Prácticas Educativas',

    '\n*QUINTO AÑO*',
    '29 Residencia',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifProfEduSalud.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowLicEducSalud = addKeyword(['05']).addAnswer([
    '📄 *Licenciatura en Educación para la Salud*',
    'Sede: San Salvador de Jujuy y San Pedro',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Introducción a la Educación para la Salud',
    '2	Psicología Evolutiva',
    '3	Antropología Filosófica',
    '4	Ecología Humana',
    '5	Psicología Social',
    '6	Pedagogía',
    '7	Antropología Social y Cultural',

    '\n*SEGUNDO AÑO*',
    '8	Problemática Sanitaria I',
    '9 Comunicación',
    '10 Didáctica',
    '11 Salud y Salud Pública',
    '12 Tecnología Educativa',
    '13 Epidemiología Y Estadística',

    '\n*TERCER AÑO*',
    '14 Problemática Sanitaria II',
    '15 Investigación Social',
    '16 Planeamiento de la Educación para la Salud',
    '17 Organización y Desarrollo de la Comunidad',
    '18 Legislación Aplicada',
    '19 Salud Ocupacional',

    '\n*CUARTO AÑO*',
    '20 Trabajo de Campo y Residencia',

    '\n*QUINTO AÑO*',
    '21 Seminario de Integración Metodológica',
    '22 Trabajo de Campo con Proyecto Final',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifLicEduSalud.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowLicComSocial = addKeyword(['04']).addAnswer([
    '📄 *Profesorado y Licenciatura en Ciencias de la Educación*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Teoría y Problemática de la Comunicación Social I',
    '2	Historia Social de la Cultura',
    '3	Filosofía y su Problemática',
    '4	Taller de Comprensión y Producción de Texto Periodístico',
    '5	Psicología Social',
    '6	Fuentes de Información y Documentación (Seminario)',
    '7	Introducción a la Problemática Periodística',
    '8	Taller de Producción Gráfica',
    
    '\n*SEGUNDO AÑO*',
    '9 Lingüística',
    '10 Seminario de Tecnología de la Comunicación Social',
    '11 Taller de Redacción Periodística',
    '12 *Taller Optativo:*',
    '*Producción Televisiva I',
    '*Tecnología y Producción Radiofónica I',
    '*Taller de Fotografía I',
    '13 Sociología de la Comunicación Social',
    '14 Geografía Económica y Política Americana',
    '15 Taller de Publicidad y Propaganda',
    '16 *Taller Optativo:*',
    '*Producción Televisiva II',
    '*Tecnología y Producción Radiofónica II',
    '*Taller de Fotografía II',
    
    '\n*TERCER AÑO*',
    '17 Economía Política y Problemática Económica Argentina',
    '18 Antropología Social y Cultural',
    '19 *Taller Optativo:*',
    '*Audio-Visual/Gráfica',
    '20 Historia Política, Económica y Socail de América y Argentina',
    '21 Estadística',
    '22 Análisis del Discurso',
    '23 Epistemología',
    'Acreditación de 2 niveles de Inglés y Otro Idioma extanjero moderno: _TÍTULO INTERMEDIO: TÉCNICO EN COMUNICACIÓN SOCIAL_',
    
    '\n*CUARTO AÑO*',
    '24 Teoría y Problmática de la Comunicación Social II',
    '25 Planificación en Comunicación Social',
    '26 Metodología de la Investigación',
    '27 Análisis de la Realidad Contemporánea Comunicacional (Seminario)',
    '28 Comunicación y Educación (Seminario)',
    '29 Comunicación Alternatica (Seminario)',
    '30 Ética y Legislación de la Información',
    '31 Seminarios de Formación Específica:',
    '*(Áreas) - Turística',
    '*Deportiva',
    '*Científica',
    '*Legislativa',
    '*Política',
    '*Educatica',
    '*Otros',
    '32 Residencia Profesional',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifLicComSocial.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowProfCienciaEduacion = addKeyword(['03']).addAnswer([
    '📄 *Profesorado y Licenciatura en Ciencias de la Educación*',
    'Sede: San Salvador de Jujuy y San Pedro',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Pensamiento Científico',
    '2	Problemática Educativa',
    '3	Problemática Filosófica',
    '4	Sociología General',
    '5	Optativo: Area Socio-Cultural',
    '6	Psicología General',
    
    '\n*SEGUNDO AÑO*',
    '7 Economía',
    '8 Biología del Aprendizaje',
    '9 Historia Social de la Eduación',
    '10 Epistemología',
    '11 Sociología de la Educación',
    '12 Psicología Evolutiva I',
    
    '\n*TERCER AÑO*',
    '13 Psicología Evolutiva II',
    '14 Psicología Educacional',
    '15 Historia de la Educación Argentina y Latinoamericana',
    '16 Política Educacional y Legislación',
    '17 Filosofía de la Eduación',
    '18 Didáctica General',
    '19 Psicología Social',
    
    '\n*CUARTO AÑO*',
    '20 Teoría y Metodología de la Investigación Educativa',
    '21 Planeamiento de la Educación',
    '22 Didáctica de las Áreas Disciplinares',
    '23 Teoría y Desarrollo del curriculum',
    '24 Organización y Administración Educacional',
    '25 Optativo: Área Comunicacional',
    '26 Análisis Institucional',
    
    '\n*QUINTO AÑO*',
    '27 Dificultades del Aprendizaje',
    '28 Educación Especial',
    '29 Orientación e Intervención Pedagógica Institucional',
    '30 Eduación no Formal',
    '31 Universidad y Formación Docente',
    '32 Práctica y Residencia (1) *PARA EL TÍTULO DE PROFESOR EN CIENCIAS DE LA EDUCACIÓN*',
    '33 (1) Trabajo de Campo e Investigación (Trabajo Final) *PARA EL TÍTULO DE LICENCIADO EN CIENCIAS DE LA EDUCACIÓN*',

    '\n(1): Para inscribirse en estos Módulos el alumno deberá tener aprobadas las materias de 4° Año y Regularizadas las de 5°. Para su acreditación se exigirá la previa aprobación de todos los módulos.',
    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifProfLicCiaEdu.html',
    '\n*Menu* Para volver al Menu principal.',
    '\n*Carreras* Para mostrar todas las carreras.',
])
const flowAntrop = addKeyword(['02']).addAnswer([
    '📄 *Licenciatura en Antropología*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1 Introducción a las Ciencias Antropológicas',
    '2 Antropología Biológica I',
    '3 Geología del Cuaternario',
    '4 Antropología Social y Cultural',
    '5 Prehistoria General',

    '\n*SEGUNDO AÑO*',
    '6 Etnografía Americana',
    '7 Teoría e Historia de la Antropología',
    '8 Arqueología Americana',
    '9 Sociedades Campesinas',
    '10 Organización Social y Parentesco',

    '\n*TERCER AÑO*',
    '11 Antropología Biológica II',
    '12 Metodología y Técnica de la Investigación Arqueológica',
    '13 Arqueología Argentina',
    '14 Fundamentos de Análisis Matemáticos',
    '15 Teoría e Investigación en Antropología Social',

    '\n*CUARTO AÑO*',
    '16 Etnohistoria',
    '17 Lingüística General',
    '18 Antropología de las Sociedades Complejas',
    '19 Estadística',

    '\n*MATERIAS OPTATIVAS*',
    'Filosofía y su Problemática',
    'Psicología Social',
    'Biología del Aprendizaje',
    'Sociología General',
    'Sociología de la Educación (correlativa con Sociología General)',
    'Psicología General',
    'Historia Social',
    'Metodología y Técnica de la Investigación Histórica I (*)',
    'Metodología y Técnica de la Investigación Histórica II (*)',
    'Antropología Filosófica',
    'Epistemología',
    'Economía',
    '_(*) No son de dictado permanente_',

    '\n*IDIOMAS*',
    'Dos niveles de Inglés Técnico',

    '\n*CICLO SUPERIOR*',
    'Dos Seminarios',
    'Cuatro Seminarios relacionados con el área elegida',

    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifLicAntropologia.html',
    '\n*Carreras* Para mostrar todas las carreras.',
    '\n*Menu* Para volver al Menu principal.',
])
const flowComunicacionDigital = addKeyword(['01', 'digital']).addAnswer([
    '📄 *Tecnicatura en Comunicación Digital Convergente*',
    'Sede: San Salvador de Jujuy',
    '📄 Materias de la carrera',
    '\n*PRIMER AÑO*',
    '1	Enfoques de la Comunicación Digital (Anual)',
    '2	Seminario Tecnología de la Comunicación (1 Cuat.)',
    '3	Taller de Producción y Comprensión de Textos Periodísticos 1 Cuat.',
    '4	Procesos Culturales Digitales I	(2 correlativa 2 Cuat.)',
    '5	Sociología de la Comunicación (2 Cuat.)',
    '6	Fuentes de Información y Documentación - Seminario (2 Cuat.)',
    '7	Taller de Producción Gráfica (2 Cuat.)',
    
    '\n*SEGUNDO AÑO*',
    '8	Procesos Culturales Digitales II (1,4 correlativa 1 Cuat.)',
    '9	Seminario de Periodismo Digital	(2,3,7 correlativa 1 Cuat.)',
    '10	Taller de Televisión I (2 correlativa 1 Cuat.)',
    '11	Taller de Producción Radiofónica I (1 Cuat.)',
    '12	Narrativas Transmedia (2,3,7 correlativa 2 Cuat.)',
    '13	Taller de Televisión II	10 (10 correlativa 2 Cuat.)',
    '14	Taller de Producción Radiofónica (11 correlativa 2 Cuat.)',
    '15	Taller de Publicidad y Propaganda (2 Cuat.)',
    
    '\n*TERCER AÑO*',
    '16	Problemática de la Convergencia Digital (8 correlativa 1 Cuat.)',
    '17	Audiencias Transmediales (5 correlativa 1 Cuat.)',
    '18	Gestión de Medios Digitales (8 correlativa 1 Cuat.)',
    '19	Social Media Marketing (15 correlativa 1 Cuat.)',
    '20	Periodismo de Datos	(6,9 correlativa 2 Cuat.)',
    '21	Seminario de Diseño Multimedial (12 correlativa 2 Cuat.)',
    '22	Comunicación Digital con Perspectiva de Género (2 Cuat.)',
    '23	Seminario Integrador de Práctica Digital Transmedial (1 al 15 correlativa Anual)',
    
    '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/ifTecComDigConv.html',
    '\n*ofertas* Para mostrar todas las carreras.',
    '\n*Menu* Para volver al Menu principal.',
])
const flowCarreras = addKeyword(['carreras', 'car', 'Ofertas', 'ofertas', 'academica']).addAnswer(
    [
        '📝Todas las *Carreras* de la Facultad de Humanidades',
        '📄01 Tecnicatura en Comunicación Digital Convergente',
        '📄02 Licenciatura en Antropología',
        '📄03 Licenciatura en Ciencias de la Educación',
        '📄04 Licenciatura en Comunicación Social',
        '📄05 Licenciatura en Educación para la Salud',
        '📄06 Prof. en Educación para la Salud',
        '📄07 Prof. y Lic. en Filosofía',
        '📄08 Licenciatura en Historia',
        '📄09 Profesorado en Historia',
        '📄10 Profesorado en Letras',
        '📄11 Licenciatura en Letras',
        '📄12 Tec. y Lic. en Turismo',
        '📄13 Lic. en Trabajo Social',
        '📄14 Tec. en Gestión y Producción Editorial',
        'Para más info, visitanos en: https://www.fhycs.unju.edu.ar/ingreso/index.html',
        '\n*Escriba un numero* para ver el plan de estudio de esa materia.',
        '\n*Menu* Para volver al Menu principal.',
    ],null, null, [flowComunicacionDigital, flowAntrop, flowLicComSocial, flowProfCienciaEduacion, flowLicEducSalud, flowLicEnHistoria, flowProfYLicFilosofia, flowProfEnLetras, flowProfEducSalud, flowLicTrabajoSocial, flowProfHistoria, flowTecGestionProducEditorial, flowTecLicTurismo, flowLicLetras])

const flowCalAca = addKeyword(['Calendario', 'cal']).addAnswer(
    [
        '📆 *Calendario Académico 2024*',
        '*PREINSCRIPCIÓN POR CARRERA INGRESO 2024*',
        'Primera etapa: Desde 01/10/23 al 31/12/2023 (Por Internet)',
        'Segunda etapa: Desde el 05/02/24 al 29/02/2024 (Por Internet)',
        'En caso de continuar la demanda se habilitará nueva etapa en el sistema',
        
        '\n*INSCRIPCIÓN POR CARRERA INGRESO 2024 EN DIRECCIÓN ALUMNOS*',
        'Primera etapa: Desde el 01/12/2023 al 20/12/2023 , según turnos establecidos por Internet',
        'Segunda etapa: Desde el 05/02/2024 al 22/03/2024, según turnos establecidos por Internet',
        'En caso de que a la fecha establecida no se hubiera completado la demanda se habilitará una 3° etapa en el sistema',
        
        '\n*INGRESO 2024 - JORNADAS DE AMBIENTACIÓN (Todas las Sedes)*',
        'Desde el 05/02/2024 al 08/03/2024',
        
        '\n*REINSCRIPCIÓN ANUAL (Por Internet)*',
        'Desde el 11/03/24 al 17/03/2024',
        
        '\n*INSCRIPCIÓN POR MATERIA PARA EL PRIMER CUATRIMESTRE Y ANUALES*',
        'Desde el 11/03/24 al 17/03/2024 (Por Internet)',
        
        '\n*PERÍODO RECESO DE INVIERNO*',
        'Desde 15/07/24 al 26/07/2024',
        
        '\n*INSCRIPCIÓN POR MATERIAS PARA EL SEGUNDO CUATRIMESTRE* (Por Internet):',
        'Desde 05/08/24 al 09/08/2024',
        
        '\n*SEGUNDO CUATRIMESTRE (16 SEMANAS)*',
        'Inicio: : 12 de AGOSTO 2024',
        'Finalización: 29 de Noviembre 2024',
        
        '\n*TURNOS DE EXÁMENES 2024*',
        '*TURNOS:* 1º MAYO',
        '*FECHAS:* 13/05 al 17/05/2024',
        '*INSCRIPCIÓN:* 03/05 al 07/05/2024',
        '*BORRADO:* 03/05 al 15/05/2024',
        
        '\n*TURNOS:* 2º JULIO',
        '*FECHAS:* 05/07 al 12/07/2024',
        '*INSCRIPCIÓN:* 28/06 al 02/07/2024',
        '*BORRADO:* 28/06 al 10/07/2024',
        
        '\n*TURNOS:* 3º AGOSTO',
        '*FECHAS:* 05/08 al 09/08/2024',
        '*INSCRIPCIÓN:* 26/07 al 30/07/2024',
        '*BORRADO:* 26/07 al 07/08/2024',
        
        '\n*TURNOS:* 4º SEPTIEMBRE',
        '*FECHAS:* 09/09 al 13/09/2024',
        '*INSCRIPCIÓN:* 30/08 al 03/09/2024',
        '*BORRADO:* 30/08 al 11/09/2024',
        
        '\n*TURNOS:* 5º OCTUBRE',
        '*FECHAS:* 14/10 al 18/10/2024',
        '*INSCRIPCIÓN:* 04/10 al 08/10/2024',
        '*BORRADO:* 04/10 al 16/10/2024',
        
        '\n*TURNOS:* 6º NOVIEMBRE',
        '*FECHAS:* 11/11 al 15/11/2024',
        '*INSCRIPCIÓN:* 01/11 al 05/11/2024',
        '*BORRADO:* 01/11 al 13/11/2024',
        
        '\n*TURNOS:* 7º DICIEMBRE',
        '*FECHAS:* 09/12 al 13/12/2024',
        '*INSCRIPCIÓN:* 29/11 al 03/12/2024',
        '*BORRADO:* 29/11 al 11/12/2024',
        
        '\n*TURNOS:* 8º FEBRERO',
        '*FECHAS:* 17/02 al 21/02/2025',
        '*INSCRIPCIÓN:* 07/02 al 10/02/2025',
        '*BORRADO:* 07/02 al 19/02/2025',
        
        '\n*TURNOS:* 9º MARZO',
        '*FECHAS:* 10/03 al 14/03/2025',
        '*INSCRIPCIÓN:* 28/02 al 04/03/2025',
        '*BORRADO:* 28/02 al 13/03/2025',
        
        '\nPara más info, visitanos en: https://www.fhycs.unju.edu.ar/calendario_academico.html',
        '\n Escribe *Menu* Para volver al Menu principal.',
    ])

const flowTel = addKeyword(['tel', 'telefono', 'Teléfonos']).addAnswer(
    [
        '☎ Telefonos útiles',
        '📲 Despacho y Fax	3884221559',
        '📲 Decanato 3884221560',
        '📲 Vicedecanato 3884221561',
        '📲 Biblioteca 3884221603',
        '📲 División Alumnos 3884221563',
        '📲 Secretaría Académica 3884221604',
        '📲 Servicio Generales 3884221565',
        '📲 Área de Ciencias de la Salud 3884221567',
        '📲 Estadística 3884221568',
        '📲 Área de Historia 3884221569',
        '📲 Área de Lengua 3884221570',
        '📲 Secretaría de Extensión 3884221574',
        '📲 Dirección Informática 3884221571',
        '📲 Área de Cs. de la Educacion 3884221572',
        '📲 Gabinete de Arqueología 3884221573',
        '📲 Especialización en Docencia Superior 3884221574',
        '📲 Secretaría Administrativa 3884221575',
        '📲 Consejo Académico 3884221524',
        '\n📌 *Menu* Para volver al Menu principal.',
    ])
const flowCorreos = addKeyword(['Correos', 'corre']).addAnswer(
        [
            '📧 *Correos útiles* \n',
            'Dirección Informática',
            '📧 direccioninformatica@fhycs.unju.edu.ar \n',
            'Despacho (Notas)',
            '📧 dgd@fhycs.unju.edu.ar \n',
            'Secretaría de Consejo Académico',
            '📧 caf@fhycs.unju.edu.ar \n',
            'Dirección Administrativa de Secretaría Académica',
            '📧 seca@fhycs.unju.edu.ar \n',
            'Dirección Biblioteca',
            '📧 biblio@fhycs.unju.edu.ar \n',
            
            '\n📌 Escribe *Menu* Para volver al Menu principal.',
        ])

const flowPreguntasFrec = addKeyword(['preguntas', 'frecuentes', 'Preguntas']).addAnswer(
        [
            '🤔 Preguntas Frecuentes',
            '❓ *¿SE RINDE EXAMEN DE INGRESO?* ',
            'Para estudiar las distintas carreras que se dictan en nuestra unidad académica no se rinde examen de ingreso, pero los ingresantes pueden realizar las Jornadas de Ambientación y Orientación Estudiantil que se desarrollan antes del inicio del ciclo lectivo y que se informan a través de nuestro sitio web y redes sociales.\n',

            '❓ *¿SE PAGA UNA MATRÍCULA O CUOTA MENSUAL?* ',
            'No, la Facultad de Humanidades y Ciencias Sociales (FHyCS) pertenece a la Universidad Nacional de Jujuy (UNJu), por lo que no se abona matrícula de inscripción ni ningún tipo de arancel o cuota mensual.\n',

            '❓ *¿COMO ME INSCRIBO SI YA SOY ESTUDIANTE DE ESTA FACULTAD O DE OTRA UNIDAD ACADEMICA DE LA UNJU?* ',
            'Si estudias alguna carrera de la UNJu, o si alguna vez te inscribiste en una pero no cursaste, estás registrado/a en el Sistema SIU GUARANÍ, por lo que para inscribirte en una nueva carrera deberás ingresar con tu usuario y contraseña al Sistema SIU GUARANÍ. https://www.alumnos.unju.edu.ar/unju/ \n',

             '❓ *¿QUÉ PASO DEBO SEGUIR?* ',
            '1 - Ingresá con tu usuario y contraseña a: Sistema SIU GUARANÍ',
            '2 - Dirigite a: Inscripción a propuestas',
            '3 - Completá los datos del formulario',
            '4 - Posteriormente deberás presentar los requisitos de ingreso ante Dirección Alumnos. (Son los mismos que se detallan anteriormente, excepto el formulario de preinscripción, ya que al preinscribirte el Sistema no emitirá un comprobante de preinscripción a propuestas pero estarás registrado/a en el Sistema.)\n',
            'Si no contás con tu usuario y/o contraseña debes comunicarte con la Facultad donde estudias o en la unidad académica donde te inscribiste alguna vez en una carrera para recuperar tu usuario y poder ingresar al Sistema.',
            
            '\n📌 *Menu* Para volver al Menu principal.',
        ])
const flowTramites = addKeyword(['tramites', 'tramite', 'tram']).addAnswer(
        [
            '🖥️ Tramites en SIU Guaraní\n',

            '🖊️ *Preinscripción a la carrera de la Facultad* ',
            'Ingresa en: https://www.youtube.com/watch?v=-FoE4vsifb8 \n',

            '🖊️ *Inscripción a materias* ',
            'Ingresa en: https://www.youtube.com/watch?v=nzoA4M5saak \n',

            '🖊️ *Inscripción a Exámen* ',
            'Ingresa en: https://www.youtube.com/watch?v=LFJg59Ook8E \n',

            '🖊️ *Reinscripción anual de la carrera* ',
            'Ingresa en: https://www.youtube.com/watch?v=iGepuPO1Svg \n',

            '🖊️ *Autogestión de Constancias y Certificados* ',
            'Ingresa en: https://www.youtube.com/watch?v=y7182Ettzng \n',
            
            '\n📌 *Menu* Para volver al Menu principal.',
        ])

const flowPrincipal = addKeyword(['Hola', 'buenas', 'holis', 'día', 'tarde', 'noche', 'menu', 'Menú'])
    .addAnswer('🙌 Hola bienvenido a este *Chatbot* de la Facultad de Humanidades')
    .addAnswer(
        [
            '📌 Este es nuestro Menu de opciones que tenemos para mostrarte',
            '📝 Escribe *Ofertas* Académica para ver la documentación.',
            '☎ Escribe *Teléfonos* para ver los teléfonos útiles.',
            '📧 Escribe *Correo* para ver los correos útiles.',
            '📆 Escribe *Calendario*  para ver el Calensario Académico.',
            '🖥️ Escribe *Tramites* para conocer las distitnas gestiones dentro del SIU.',
            '❓ Escribe *Preguntas*  Frecuentes.',
            
        ],
        null,
        null,
        [flowTel, flowCalAca, flowCarreras, flowPreguntasFrec, flowTramites, flowCorreos]
    )

const main = async () => {
    const adapterDB = new MockAdapter()
    const adapterFlow = createFlow([flowPrincipal, flowCarreras])
    const adapterProvider = createProvider(BaileysProvider)

    createBot({
        flow: adapterFlow,
        provider: adapterProvider,
        database: adapterDB,
    })

    QRPortalWeb()
}

main()
